; Actividad 5 - Control de brazo robótico (URDF) con ESP32 (DevKit 30 pines)
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
; Cambia el puerto si Windows le asigna otro
upload_port = COM5
monitor_port = COM5
